### ISSUE TITLE
Update "overview" document of Grid Purchase Order

### ISSUE THREAD

**Issue by shannynalayna** [hyperledger/grid-docs#285]
This document: https://grid.hyperledger.org/docs/0.3/grid_purchase_order.html is a high-level overview of the Purchase Order feature. It goes a little bit in-depth to the fields of the main po struct and contains the protobuf messages for po. The content here needs to be brought up-to-date with the current implementation of purchase order

**Comment by CLEckhardt** [comment]
Closed via #287
