### ISSUE TITLE
Location Feature Overview

### ISSUE THREAD

**Issue by dplumb94** [hyperledger/grid-docs#70]
Provide a high-level description that is focused on business-level concepts and benefits. Some technical information is appropriate, but details belong in the procedure and reference material. Include links to the detailed information as appropriate.

Example: Canopy Application Framework (https://www.splinter.dev/docs/0.4/concepts/canopy_application_framework.html)

**Comment by JessieZamzow** [comment]
@dplumb94 Dave provided feedback on this PR. I believe I need one more review. If you could please give it a read-through then we can partner to integrate the points of feedback and merge content.
